Repository asc-community/AngouriMath, pull requests merged in 2021-04, with the labels that each got.

#372 Expand should be less limited
  README.md
  Sources/AngouriMath/Convenience/MathS.cs
  Sources/AngouriMath/Functions/Continuous/Solvers/EquationSolver.cs
  Sources/AngouriMath/Functions/TreeAnalyzer/Expansion.cs
  Sources/Samples/Samples/Program.cs
  Sources/Tests/DotnetBenchmark/Program.cs
Labels: Done & requires further testing, Early PR

#380 Matrices improvements
  Sources/AngouriMath/AngouriMath.csproj
  Sources/AngouriMath/Convenience/MathS.cs
  Sources/AngouriMath/Core/Entity/Omni/Entity.Matrix.cs
  Sources/Samples/Samples/Program.cs
  Sources/Tests/UnitTests/Algebra/MatrixTest.cs
Labels: Early PR

#387 Improving F# and Interactive...
  .github/workflows/CSharpTest.yml
  .github/workflows/InteractiveBuild.yml
  .github/workflows/InteractiveTest.yml
  README.md
  Sources/AngouriMath.sln
  Sources/Tests/FSharpWrapperUnitTests/Common.fs
  Sources/Tests/FSharpWrapperUnitTests/CompilationTest.fs
  Sources/Tests/FSharpWrapperUnitTests/CoreTest.fs
  Sources/Tests/FSharpWrapperUnitTests/Functions.Continuous.fs
  Sources/Tests/FSharpWrapperUnitTests/Functions.Discrete.fs
  Sources/Tests/FSharpWrapperUnitTests/Functions.Matrices.fs
  Sources/Tests/FSharpWrapperUnitTests/Functions.Order.fs
  Sources/Tests/FSharpWrapperUnitTests/Functions.Sets.fs
  Sources/Tests/FSharpWrapperUnitTests/ShortcutsTest.fs
  Sources/Tests/InteractiveWrapperUnitTests/AggressiveOperators.fs
  Sources/Tests/InteractiveWrapperUnitTests/HtmlOutput.fs
  Sources/Tests/InteractiveWrapperUnitTests/InteractiveWrapperUnitTests.fsproj
  Sources/Tests/InteractiveWrapperUnitTests/Program.fs
  Sources/Wrappers/AngouriMath.FSharp/Compilation.fs
  Sources/Wrappers/AngouriMath.FSharp/Constants.fs
  Sources/Wrappers/AngouriMath.FSharp/Core.fs
  Sources/Wrappers/AngouriMath.FSharp/Functions.fs
  Sources/Wrappers/AngouriMath.FSharp/Shortcuts.fs
  Sources/Wrappers/AngouriMath.FSharp/icon.png
  Sources/Wrappers/AngouriMath.Interactive/AggressiveOperators.fs
  Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj
  Sources/Wrappers/AngouriMath.Interactive/Main.fs
  Sources/Wrappers/AngouriMath.Interactive/icon.png
Labels: Early PR

#388 Improvements and refactoring of F# and Interactive
  Sources/AngouriMath.sln
  Sources/AngouriMath/AngouriMath.csproj
  Sources/AngouriMath/Core/Entity/Omni/Entity.Matrix.cs
  Sources/Samples/FSharpPlayground/Program.fs
  Sources/Tests/FSharpWrapperUnitTests/ShortcutsTest.fs
  Sources/Tests/InteractiveWrapperUnitTests/AggressiveOperators.fs
  Sources/Tests/InteractiveWrapperUnitTests/HtmlOutput.fs
  Sources/Tests/UnitTests/Algebra/MatrixTest.cs
  Sources/Wrappers/AngouriMath.FSharp/AngouriMath.FSharp.fsproj
  Sources/Wrappers/AngouriMath.FSharp/Functions.fs
  Sources/Wrappers/AngouriMath.FSharp/Shortcuts.fs
  Sources/Wrappers/AngouriMath.FSharp/icon.png
  Sources/Wrappers/AngouriMath.Interactive/AggressiveOperators.fs
  Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj
  Sources/Wrappers/AngouriMath.Interactive/KernelExtension.fs
  Sources/Wrappers/AngouriMath.Interactive/Main.fs
  Sources/Wrappers/AngouriMath.Interactive/Repack.ps1
  Sources/Wrappers/AngouriMath.Interactive/icon.png
  Sources/icon.png
Labels: Early PR

#390 Minor improvements of implicit operators
  .github/workflows/Benchmark.yml
  .github/workflows/CPPBuild.yml
  .github/workflows/CPPTest.yml
  .github/workflows/CSharpBuild.yml
  .github/workflows/CSharpTest.yml
  .github/workflows/EverythingBuild.yml
  .github/workflows/FSharpBuild.yml
  .github/workflows/FSharpTest.yml
  .github/workflows/InteractiveBuild.yml
  .github/workflows/InteractiveTest.yml
  README.md
  Sources/AngouriMath/Core/Entity/Continuous/Entity.Continuous.Definition.cs
  Sources/AngouriMath/Core/Entity/Continuous/Entity.Continuous.Number.Definition.cs
  Sources/AngouriMath/Core/Entity/Entity.ImplicitOperators.cs
  Sources/Samples/Samples/Playground.csproj
  Sources/Samples/Samples/Program.cs
  Sources/Tests/UnitTests/Common/ImplicitOperators.cs
  Sources/Wrappers/AngouriMath.CPP.Exporting/AngouriMath.CPP.Exporting.csproj
  Sources/Wrappers/AngouriMath.FSharp/Core.fs
Labels: Early PR

#393 Force user to use ^ symbol to power a number
  Sources/AngouriMath/Convenience/MathS.cs
  Sources/AngouriMath/Core/Parser.cs
  Sources/Tests/UnitTests/Core/Settings.cs
Labels: Early PR, Proposal
